name: water-network-tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r OptiChat/requirements.txt

      - name: Run pumped-storage regression suite
        run: |
          cd OptiChat
          pytest tests/test_water_network_enhancements.py tests/test_water_network_examples.py
